👾 Fix a crush when navigation to RegisterActivity
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sunrise/com.example.sunrise.Register}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.